# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import vsq.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coalizione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('colore', vsq.fields.RGBColorField(max_length=7)),
                ('ordine', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Coalizioni',
            },
        ),
        migrations.CreateModel(
            name='Domanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text=b'Valore suggerito, generato dal testo. Deve essere unico.', max_length=60, unique=True)),
                ('testo', models.TextField()),
                ('testo_html', models.TextField(editable=False)),
                ('approfondimento', models.TextField(blank=True, null=True)),
                ('approfondimento_html', models.TextField(blank=True, editable=False, null=True)),
                ('accompagno', models.TextField(blank=True, null=True)),
                ('accompagno_html', models.TextField(blank=True, editable=False, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('ordine', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25)])),
            ],
            options={
                'ordering': ['ordine'],
                'verbose_name_plural': 'Domande',
            },
        ),
        migrations.CreateModel(
            name='EarlyBird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(error_messages={b'unique': b'Attenzione: indirizzo email gi\xc3\xa0 inserito.'}, max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Utenti Early Bird',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domanda', models.TextField()),
                ('domanda_html', models.TextField(editable=False)),
                ('risposta', models.TextField()),
                ('risposta_html', models.TextField(editable=False)),
                ('ordine', models.IntegerField()),
                ('slug', models.SlugField(help_text=b'Valore suggerito, generato dal testo. Deve essere unico.', max_length=60, unique=True)),
            ],
            options={
                'ordering': ['ordine'],
                'verbose_name_plural': 'Faq',
            },
        ),
        migrations.CreateModel(
            name='Partito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominazione', models.CharField(max_length=255, unique=True)),
                ('party_key', models.CharField(max_length=255, unique=True)),
                ('sigla', models.CharField(max_length=32, unique=True)),
                ('responsabile_nome', models.CharField(blank=True, max_length=128, null=True)),
                ('responsabile_email', models.EmailField(blank=True, max_length=128, null=True)),
                ('risposte_at', models.DateField(blank=True, null=True)),
                ('sito', models.URLField(blank=True, null=True)),
                ('simbolo', models.ImageField(blank=True, null=True, upload_to=b'simboli')),
                ('slug', models.SlugField(blank=True, max_length=60, null=True, unique=True)),
                ('coord_x', models.FloatField(blank=True, default=0.0)),
                ('coord_y', models.FloatField(blank=True, default=0.0)),
                ('twitter_hashtag', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_user', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=255, null=True)),
                ('leader', models.CharField(blank=True, max_length=255, null=True)),
                ('nonorig', models.BooleanField(default=False, verbose_name=b'Non originale')),
                ('coalizione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsq.Coalizione')),
            ],
            options={
                'verbose_name': 'Candidato sindaco',
                'verbose_name_plural': 'Candidati sindaco',
            },
        ),
        migrations.CreateModel(
            name='RispostaPartito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risposta_int', models.SmallIntegerField(choices=[(-3, b'Molto contrario/a'), (-2, b'Contrario/a'), (-1, b'Tendenzialmente contrario/a'), (1, b'Tendenzialmente favorevole'), (2, b'Favorevole'), (3, b'Molto favorevole')], verbose_name=b'Risposta')),
                ('risposta_txt', models.TextField(blank=True, null=True, verbose_name=b'Risposta testuale')),
                ('nonorig', models.BooleanField(default=False, verbose_name=b'Non originale')),
                ('domanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsq.Domanda')),
                ('partito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsq.Partito')),
            ],
            options={
                'verbose_name_plural': 'Risposte partito',
            },
        ),
        migrations.CreateModel(
            name='RispostaUtente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risposta_int', models.SmallIntegerField(choices=[(-3, b'Molto contrario/a'), (-2, b'Contrario/a'), (-1, b'Tendenzialmente contrario/a'), (1, b'Tendenzialmente favorevole'), (2, b'Favorevole'), (3, b'Molto favorevole')], verbose_name=b'Risposta')),
                ('domanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsq.Domanda')),
            ],
            options={
                'verbose_name_plural': 'Risposte utente',
            },
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.CharField(max_length=255, unique=True)),
                ('nickname', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=128, null=True)),
                ('agent', models.TextField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('coord', models.TextField(blank=True, null=True)),
                ('has_sent_emails', models.BooleanField(default=False)),
                ('wants_newsletter', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Utenti',
            },
        ),
        migrations.AddField(
            model_name='rispostautente',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsq.Utente'),
        ),
    ]
