# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 20:43
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.text import slugify


def slugify_party_key(apps, schema_editor):
    # We can't import the Partito model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Partito = apps.get_model("vsq", "Partito")
    for party in Partito.objects.all():
        party.party_key = slugify(party.party_key)
        party.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vsq', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(slugify_party_key),
        migrations.AlterField(
            model_name='partito',
            name='party_key',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
