# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsq', '0003_partito_is_module_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partito',
            name='balance_sheet_document',
        ),
        migrations.RemoveField(
            model_name='partito',
            name='election_expenses_document',
        ),
        migrations.AlterField(
            model_name='partito',
            name='balance_sheet',
            field=models.URLField(blank=True, max_length=500, verbose_name=b'Dichiarazione patrimoniale'),
        ),
        migrations.AlterField(
            model_name='partito',
            name='election_expenses',
            field=models.URLField(blank=True, max_length=500, verbose_name=b'Spese elettorali'),
        ),
        migrations.AlterField(
            model_name='partito',
            name='is_module_open',
            field=models.BooleanField(default=True, verbose_name=b'Questionario aperto'),
        ),
    ]
